backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow

media_folder: static/img/uploads

public_folder: /img/uploads

# site_url: https://www.robinsonsoccer.com

# display_url: robinsonsoccer.com

collections:
  - label: Example
    name: "example"
    create: true
    folder: content/example
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Heading, name: heading, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - label: Main Content
        name: main content
        widget: object
        fields:
          - label: Text Body
            name: text body
            hint: "Create a new text widget for each paragraph"
            widget: list
            fields:
              - {label: Text, name: text, widget: text, required: false}
          - {label: Image, name: image, widget: image, required: false}
      - {label: Body, name: body, widget: markdown, required: false, hint: Optional way to input text and images into main content area}




          
# Announcements - start
  - label: "Announcements"
    name: "announcements"
    files:
      - file: "config.yaml"
        label: "Banner"
        name: "banner"
        fields:
          - label: Content
            name: "params"
            widget: object
            fields:
              - {label: Line One, name: "lineOne", widget: string}
              - {label: Line Two, name: "lineTwo", required: false, widget: string}
              - {label: Line Three, name: "lineThree", widget: string}
# Announcements - end
# Club Home - start
  - label: "Club Homepage"
    name: "club homepage"
    files:
      - file: "content/club/_index.md"
        label: "Club Home"
        name: "club home"
        fields:
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: body, widget: markdown}
          - label: Club Info
            name: info
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
# Club Home - end 
# Club Divisions - start
  - label: Club Divisions
    name: "divisions"
    files:
      - file: "content/club/u12/roster.md"
        label: "U12 Roster"
        name: "u12 roster"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown, required: false}
      - file: "content/club/u12/schedule.md"
        label: "U12 Schedule"
        name: "u12 schedule"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: body, widget: markdown, required: false}
      - file: "content/club/u14/roster.md"
        label: "U14 Roster"
        name: "u14 roster"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: body, widget: markdown, required: false}
      - file: "content/club/u14/schedule.md"
        label: "U14 Schedule"
        name: "U14 schedule"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: body, widget: markdown, required: false}
      - file: "content/club/u18/roster.md"
        label: "U18 Roster"
        name: "u18 roster"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: body, widget: markdown, required: false}
      - file: "content/club/u18/schedule.md"
        label: "U18 Schedule"
        name: "u18 schedule"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: body, widget: markdown, required: false}
# Club Divisions - end
# Club Registration
  - label: Club Registration
    name: "club registration"
    files:
      - file: content/club/registration/index.md
        label: Registration
        name: "registration"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown}
# Club Info - start
  - label: Club Info
    name: "club info"
    files:
      - file: "content/club/info/fundraisers.md"
        label: "Fundraisers"
        name: "fundraisers"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: body, widget: markdown, required: false}
      - file: "content/club/info/rules.md"
        label: "Rules"
        name: "rules"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: body, widget: markdown}
      - file: "content/club/info/uniforms.md"
        label: "Uniforms"
        name: "Uniforms"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: body, widget: markdown, required: false}
      - file: "content/club/info/sponsors.md"
        label: "Sponsors"
        name: "sponsors"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: date, widget: datetime}
          - {label: Body, name: body, widget: markdown, required: false}
# Club Info - end
# Youth Home - start
  - label: Youth Homepage
    name: "youth homepage"
    files:
      - file: "content/youth/_index.md"
        label: "Youth Home"
        name: "youth home"
        fields: 
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: body, widget: markdown}
# Youth Home - end
# Youth Leagues - start
  - label: Youth Leagues
    name: "youth leagues"
    files:
      - file: content/youth/leagues/beginner/teams.md
        label: Beginner/U6 Teams
        name: "u6 teams"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown, required: false}
      - file: content/youth/leagues/beginner/schedule.md
        label: Beginner/U6 Schedule
        name: "u6 schedule"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown, required: false}
      - file: content/youth/leagues/major/teams.md
        label: Major/U8 Teams
        name: "u8 teams"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown, required: false}
      - file: content/youth/leagues/major/schedule.md
        label: Major/U8 Schedule
        name: "u8 schedule"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown, required: false}
      - file: content/youth/leagues/super/teams.md
        label: Super/U10 Teams
        name: "u10 teams"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown, required: false}
      - file: content/youth/leagues/super/schedule.md
        label: Super/U10 Schedule
        name: "u10 schedule"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown, required: false}
      - file: content/youth/leagues/super/standings.md
        label: Super/U10 Standings
        name: "u10 standings"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown, required: false}
      - file: content/youth/leagues/premier/teams.md
        label: Premier/U13 Teams
        name: "u13 teams"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown, required: false}
      - file: content/youth/leagues/premier/schedule.md
        label: Premier/U13 Schedule
        name: "u13 schedule"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown, required: false}
      - file: content/youth/leagues/premier/standings.md
        label: Premier/U13 Standings
        name: "u13 standings"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown, required: false}
# Youth Leagues - end
# Club Registration
  - label: Youth Registration
    name: "youth registration"
    files:
      - file: content/youth/registration/index.md
        label: Registration
        name: "registration"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - { label: Publish Date, name: "date", widget: datetime}
          - { label: Main Content, name: "body", widget: markdown}
# Youth Info - start
  - label: Youth Info
    name: "youth info"
    files:
      - file: content/youth/info/fields.md
        label: Fields
        name: "fields"
        fields: 
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: date, widget: datetime}
          - {label: Main Content, name: "body", widget: markdown}
      - file: content/youth/info/location.md
        label: Location
        name: "location"
        fields: 
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: date, widget: datetime}
          - {label: Main Content, name: "body", widget: markdown}
      - file: content/youth/info/fan-gear.md
        label: Fan Gear
        name: "fan gear"
        fields: 
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: date, widget: datetime}
          - {label: Main Content, name: "body", widget: markdown}
      - file: content/youth/info/rules.md
        label: Rules
        name: "rules"
        fields: 
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: date, widget: datetime}
          - {label: Main Content, name: "body", widget: markdown}
      - file: content/youth/info/equipment.md
        label: Equipment
        name: "equipment"
        fields: 
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: date, widget: datetime}
          - {label: Main Content, name: "body", widget: markdown}
      - file: content/youth/info/uniforms.md
        label: Uniforms
        name: "uniforms"
        fields: 
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: date, widget: datetime}
          - {label: Main Content, name: "body", widget: markdown}
      # Working on coaching - URL's
      - file: content/youth/info/coaching.md
        label: Coaching
        name: "coaching"
        fields: 
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: date, widget: datetime}
          - {label: Main Content, name: "body", widget: markdown}
      - file: content/youth/info/faq.md
        label: FAQ
        name: "faq"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Main Content, name: "body", widget: markdown}
# Youth Info - end
# Youth Sponsors - start
  - label: Youth Sponsors
    name: sponsors
    folder: /content/youth/sponsors
    create: false
    media_folder: ""
    public_folder: ""
    fields:
      - {label: Heading, name: heading, widget: string}
      - {label: Intro, name: text, widget: text}
      - label: Sponsor Form Link
        name: link
        widget: object
        fields:
          - {label: Link Text, name: linkText, widget: string}
          - {label: URL, name: url, widget: string}
      - label: Images
        name: images
        widget: list
        fields:
          - label: Sponsor Image
            name: sponsorImg
            widget: image
            fields:
              - label: Sponsor Link
                name: link
                widget: object
                fields:
                  - {label: URL, name: url, widget: string, required: false}

