backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: static/img/uploads
public_folder: /img/uploads
site_url: https://www.robinsonsoccer.com
display_url: robinsonsoccer.com

collections:
  - name: 'club homepage'
    label: 'Club Homepage'
    description: 'Landing page for club soccer'
    file: 'content/club/_index.md'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }