backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: static/img/uploads

public_folder: /img/uploads

# site_url: https://www.robinsonsoccer.com

# display_url: robinsonsoccer.com

collections:
# Announcements - start
  - label: "Announcements"
    name: "announcements"
    files:
      - file: "config.yaml"
        label: "Banner"
        name: "banner"
        fields:
          - label: Content
            name: "params"
            widget: object
            fields:
              - {label: Line One, name: "lineOne", widget: string}
              - {label: Line Two, name: "lineTwo", widget: string}
              - {label: Line Three, name: "lineThree", widget: string}
# Announcements - end
# Club Home - start
  - label: "Club"
    name: "club"
    files:
      - file: "content/club/_index.md"
        label: "Club Homepage"
        name: "club home"
        fields:
          - {label: Publish Date, name: "date", widget: datetime}
          - label: Images and Flyers
            name: "flyer"
            widget: list
            fields:
              - {label: Heading, name: "heading", widget: string}
              - {label: Image, name: "image", widget: image}
              - {label: Description, name: "description", widget: string}
              - {label: Update, name: "update", widget: string}
              - label: Registration Link
                name: "registration"
                widget: object
                fields:
                  - {label: URL, name: regURL, widget: string}
                  - {label: Link Text, name: regText, widget: string}
              - label: Payment Link
                name: "payment"
                widget: object
                fields:
                  - {label: URL, name: payURL, widget: string}
                  - {label: Link Text, name: payText, widget: string}
# Club Home - end 
# Club Divisions - start
  - label: Club Divisions
    name: "divisions"
    files:
      - file: "content/club/u12/roster.md"
        label: "U12 Roster"
        name: "u12 roster"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Roster, name: "roster", widget: file}
          - {label: Body, name: "body", widget: markdown}

      - file: "content/club/u12/schedule.md"
        label: "U12 Schedule"
        name: "u12 schedule"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Schedule, name: "schedule", widget: file}

      - file: "content/club/u14/roster.md"
        label: "U14 Roster"
        name: "u14 roster"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Roster, name: "roster", widget: file}

      - file: "content/club/u14/schedule.md"
        label: "U14 Schedule"
        name: "U14 schedule"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Schedule, name: "schedule", widget: file}

      - file: "content/club/u18/roster.md"
        label: "U18 Roster"
        name: "u18 roster"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Roster, name: "roster", widget: file}

      - file: "content/club/u18/schedule.md"
        label: "U18 Schedule"
        name: "u18 schedule"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Schedule, name: "schedule", widget: file}
# Club Divisions - end
# Club Misc. - start
  - label: Club Misc.
    name: "miscellaneous"
    files:
      - file: "content/club/registration/index.md"
        label: "Registration"
        name: "registration"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}

      - file: "content/club/info/fundraisers.md"
        label: "Fundraisers"
        name: "fundraisers"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Image, name: Image, widget: image}
          
      - file: "content/club/info/rules.md"
        label: "Rules"
        name: "rules"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: body, widget: markdown}

      - file: "content/club/info/uniforms.md"
        label: "Uniforms"
        name: "Uniforms"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Image, name: image, widget: image}

      - file: "content/club/info/sponsors.md"
        label: "Sponsors"
        name: "sponsors"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: date, widget: datetime}
          - {label: Body, name: body, widget: markdown}
# Club Misc. - end

  - label: Youth
    name: "youth"
    files:
      - file: "content/youth/_index.md"
        label: "Youth Homepage"
        name: "youth homepage"
        fields: 
          - {label: Publish Date, name: "date", widget: datetime}
          - label: Images and Flyers
            name: "flyer"
            widget: list
            fields:
              - {label: Heading, name: "heading", widget: string}
              - {label: Image, name: "image", widget: image}
              - {label: Description, name: "description", widget: string}
              - {label: Update, name: "update", widget: string}
              - label: Registration Link
                name: "registration"
                widget: object
                fields:
                  - {label: URL, name: "regURL", widget: string}
                  - {label: Link Text, name: "regText", widget: string}
              - label: Payment Link
                name: "payment"
                widget: object
                fields:
                  - {label: URL, name: "payURL", widget: string}
                  - {label: Link Text, name: "payText", widget: string}
# Youth Leagues - start
      - file: content/youth/leagues/beginner/teams.md
        label: Beginner/U6 Teams
        name: "u6 teams"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: "body", widget: markdown}

      - file: content/youth/leagues/beginner/schedule.md
        label: Beginner/U6 Schedule
        name: "u6 schedule"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: "body", widget: markdown}

      - file: content/youth/leagues/major/teams.md
        label: Major/U8 Teams
        name: "u8 teams"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: "body", widget: markdown}

      - file: content/youth/leagues/major/schedule.md
        label: Major/U8 Schedule
        name: "u8 schedule"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: "body", widget: markdown}

      - file: content/youth/leagues/super/teams.md
        label: Super/U10 Teams
        name: "u10 teams"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: "body", widget: markdown}

      - file: content/youth/leagues/super/schedule.md
        label: Super/U10 Schedule
        name: "u10 schedule"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: "body", widget: markdown}

      - file: content/youth/leagues/super/standings.md
        label: Super/U10 Standings
        name: "u10 standings"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: "body", widget: markdown}

      - file: content/youth/leagues/premier/teams.md
        label: Premier/U13 Teams
        name: "u13 teams"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: "body", widget: markdown}

      - file: content/youth/leagues/premier/schedule.md
        label: Premier/U13 Schedule
        name: "u13 schedule"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: "body", widget: markdown}

      - file: content/youth/leagues/premier/standings.md
        label: Premier/U13 Standings
        name: "u13 standings"
        fields:
          - { label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: "body", widget: markdown}
# Youth Leagues - end
