backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: static/img/uploads

public_folder: /img/uploads

# site_url: https://www.robinsonsoccer.com

# display_url: robinsonsoccer.com

collections:
  - label: "Site"
    name: "site"
    files:
      - file: "config.yml"
        label: "Banner"
        name: "banner"
        fields: 
          - {label: Heading, name: "bannerHeading", widget: string}
          - {label: Body, name: "bannerBody", widget: string}
          - {label: Footer, name: "bannerFooter", widget: string}

  - label: "Club"
    name: "club"
    files:
      - file: "content/club/_index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Flyer1, name: "flyer1", widget: object, fields: [
              {label: Heading, name: "heading", widget: string},
              {label: Image, name: "img", widget: image},
              {label: Caption, name: "caption", widget: string},
              {label: Update, name: "update", widget: string}]}
          - {label: Registration Link, name: register, widget: object, fields: [
              {label: Link Text, name: text, widget: string},
              {label: URL, name: url, widget: string}]}
          - {label: Payment Link, name: pay, widget: object, fields: [
              {label: Link Text, name: text, widget: string},
              {label: URL, name: url, widget: string}]}
          - {label: "Club Info", name: "clubInfo", widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: Main Content, name: body, widget: markdown}

      - file: "content/club/u12/roster.md"
        label: "U12 Roster"
        name: "u12 roster"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Roster, name: "roster", widget: file}
          - {label: Body, name: body, widget: markdown}
      - file: "content/club/u12/schedule.md"
        label: "U12 Schedule"
        name: "u12 schedule"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Schedule, name: "schedule", widget: file}

      - file: "content/club/u14/roster.md"
        label: "U14 Roster"
        name: "u14 roster"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Roster, name: "roster", widget: file}
      - file: "content/club/u14/schedule.md"
        label: "U14 Schedule"
        name: "U14 schedule"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Schedule, name: "schedule", widget: file}

      - file: "content/club/u18/roster.md"
        label: "U18 Roster"
        name: "u18 roster"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Roster, name: "roster", widget: file}
      - file: "content/club/u18/schedule.md"
        label: "U18 Schedule"
        name: "u18 schedule"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Schedule, name: "schedule", widget: file}

      - file: "content/club/registration/index.md"
        label: "Registration"
        name: "registration"
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Publish Date, name: "date", widget: datetime}

      - file: "content/club/info/fundraisers.md"
        label: "Fundraisers"
        name: "fundraisers"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Image, name: Image, widget: image}
          
      - file: "content/club/info/rules.md"
        label: "Rules"
        name: "rules"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Body, name: body, widget: markdown}

      - file: "content/club/info/uniforms.md"
        label: "Uniforms"
        name: "Uniforms"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
          - {label: Image, name: image, widget: image}

      - file: "content/club/info/sponsors.md"
        label: "Sponsors"
        name: "sponsors"
        fields:
          - {label: Heading, name: "heading", widget: string}
          - {label: Publish Date, name: date, widget: datetime}
          - {label: Body, name: body, widget: markdown}

  - name: "youth"
    label: "Youth"
    files: 
      - file: "content/youth/_index.md"
        label: "Home"
        name: "home"
        fields: 
          - {label: Title, name: "title", widget: string}
          - {label: Publish Date, name: "date", widget: datetime}
            

